AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  function95003B73:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-function95003B73
      Description: !Sub
        - Stackery Stack ${StackeryStackTagName} Environment ${StackeryEnvironmentTagName} Function ${ResourceName}
        - ResourceName: myCronJob
      CodeUri: src/function95003B73
      Handler: handler.handler
      Runtime: python2.7
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Events:
        timerBC6C4571:
          Type: Schedule
          Properties:
            Schedule: cron(0 3 * * ? *)
          Metadata:
            StackeryName: Every day at 3 am (UTC)
    Metadata:
      StackeryName: myCronJob
Parameters:
  StackeryStackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  StackeryEnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)